# Generated by Django 2.2 on 2020-09-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='products/image_default.jpg', upload_to='products'),
        ),
    ]
