# Generated by Django 2.2 on 2020-09-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200904_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='image_default.jpg', upload_to='products'),
        ),
    ]
