# Generated by Django 2.2.13 on 2020-09-07 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200904_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Categorie'),
        ),
    ]
